:- module(routes, [
    handle_evaluate/1
]).

/** <module> HTTP Routing and Request Handling (Transport Layer)
 *
 * This module defines the REST API endpoints and routes for the Prolog engine.
 * It is responsible for:
 *   1. Deserializing incoming JSON request payloads into native Prolog Dicts.
 *   2. Delegating scenario evaluation to the core domain layer (`rules`).
 *   3. Serializing the evaluation outcome into structured JSON responses conforming
 *      to the project's API contracts.
 */

:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_json)).
:- use_module('../core/rules', [evaluate_scenario/3]).

% Register POST /evaluate route with http_dispatch
:- http_handler(root(evaluate), handle_evaluate, [method(post)]).

%!  handle_evaluate(+Request) is det.
%
%   HTTP request handler for POST /evaluate. Reads the scenario JSON payload,
%   queries the core business rules for diagnosis and explanation, and returns
%   the corresponding JSON response.
%
%   @param Request HTTP request environment provided by http_dispatch.
handle_evaluate(Request) :-
    catch(
        http_read_json_dict(Request, ScenarioDict),
        ReadError,
        (
            format(user_error, '~N[ROUTES ERROR] Failed to parse request JSON: ~w~n', [ReadError]),
            reply_json_dict(_{
                status: "error",
                message: "Invalid JSON payload or missing required parameters",
                decision: "error",
                justification: []
            }, [status(400)]),
            !
        )
    ),
    (   var(ScenarioDict)
    ->  true
    ;   rules:evaluate_scenario(ScenarioDict, Decision, ExplanationList),
        format_response(Decision, ExplanationList, ResponseDict, StatusCode),
        (   StatusCode =:= 200
        ->  reply_json_dict(ResponseDict)
        ;   reply_json_dict(ResponseDict, [status(StatusCode)])
        )
    ).

%!  format_response(+Decision, +ExplanationList, -ResponseDict, -StatusCode) is det.
%
%   Helper predicate to build the response dict and determine the HTTP status
%   code based on the decision generated by the domain rules.
format_response(error, ExplanationList, ResponseDict, 400) :-
    !,
    ResponseDict = _{
        status: "error",
        message: "Invalid JSON payload or missing required parameters",
        decision: "error",
        justification: ExplanationList
    }.
format_response(Decision, ExplanationList, ResponseDict, 200) :-
    ResponseDict = _{
        status: "success",
        decision: Decision,
        justification: ExplanationList
    }.
